### ISSUE TITLE
changing the pagesize changes the order of elements returned

### ISSUE THREAD

**Issue by stuppie** [SuLab/garbanzo#6]
changing the pagesize changes the order of elements returned. That if I request Page 1 of a certain size, it has element 'A' as the first element but requesting Page 1 of another page size, element 'A' may not be the first returned.

**Comment by stuppie** [comment]
@rbruskiewich can you show me an example? This doesn't happen for me:
http://garbanzo.sulab.org/statements/?c=wd%3AQ133696&pageSize=15&pageNumber=1
http://garbanzo.sulab.org/statements/?c=wd%3AQ133696&pageSize=14&pageNumber=1
http://garbanzo.sulab.org/statements/?c=wd%3AQ133696&pageSize=20&pageNumber=1

**Comment by stuppie** [comment]
https://github.com/SuLab/garbanzo/commit/d3a552576b6fe4e8266e8ffab299e36ae223bac5

**Comment by RichardBruskiewich** [comment]
Gregg,

Please compare:

http://garbanzo.sulab.org/concepts/?keywords=ab&pageNumber=2&pageSize=7
against
http://garbanzo.sulab.org/concepts/?keywords=ab&pageNumber=1&pageSize=14

The former page of 7 items should align with elements 8 - 14 of the second results. Not sure that they do,

**Comment by stuppie** [comment]
@RichardBruskiewich Ah, I thought you were talking about the statements endpoint.
Fixed with https://github.com/SuLab/garbanzo/commit/2de9b420a56484f5d4724d9d74a5fba379d17f0b
