### ISSUE TITLE
exactmatches changes

### ISSUE THREAD

**Issue by stuppie** [SuLab/garbanzo#8]
Given an input list of CURIE identifiers of known exactly matched concepts sensa-SKOS, retrieves the list of CURIE identifiers of additional concepts that are deemed by the given knowledge source to be exact matches to one or more of the input concepts plus whichever identifiers from the input list which specifically matched these new additional concepts. If an empty set is returned, the it can be assumed that the given knowledge source does not know of any new equivalent concepts matching the input set.

**Comment by stuppie** [comment]
What is supposed to happen if the input contains curies that the data source doesn't think are equivalent to each other?
For example, if the input is [MESH:1111, MESH:2222], where both curies are present in the datasource, and have exactmatches, but are NOT equivalent to each other. 
The description says "known exactly matched concepts", so it is just assumed the concepts are exact matches and the new/related exactmacthes are still returned as expected?
@RichardBruskiewich

**Comment by RichardBruskiewich** [comment]
Excellent question Greg!  To be honest, the 'exact matches'  algorithm in the beacon-aggregator is still very much imperfect and probably inadvertently generates spurious exact matches (like the kind you note above). For now, you should just honor the contract and return the union list of the two exact matches concept lists (as you say). At some point, further iteration on this challenge will be required... it is a touch dragon to slay!
